evocom/communities/urls.py
from django.urls import path
from . import views

app_name = 'communities' 
urlpatterns = [
    path('create_community/', views.create_community, name='create_community'),
    path('community_management/', views.community_management, name='community_management'),
    path('update_community/', views.update_community, name='update_community'),
    path('show_communities/',views.show_communities, name='show_communities'),
    path('community/<int:pk>/', views.view_community, name='view_community'),
    path('community/<int:community_id>/join/', views.join_community, name='join_community'),
    path('joined_communities/',views.joined_communities, name='joined_communities'),
]

evocom/evocom/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from evocom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('users/', include('users.urls')),
    path('communities/', include('communities.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

evocom/users/urls.py
from django.urls import path
from . import views

app_name = 'users' 
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contacts', views.contacts, name='contacts'),
    path('profile/', views.user_profile, name='user_profile'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_page, name='login'),
    path('loginfn/', views.login_view, name='loginfn'),
    path('logout/', views.user_logout, name='logout'),
    path('complete-profile/', views.complete_profile, name='complete_profile'),
    path('admin_index/', views.admin_index, name='admin_index'),
    path('member_index/', views.member_index, name='member_index'),
    path('community_admin_index/', views.community_admin_index, name='community_admin_index'),
    path('forgot_password/', views.password_reset_request, name='password_reset_request'),
    path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
    path('select_user_type/', views.select_user_type, name='select_user_type'),
    path('complete_profile/', views.complete_profile, name='complete_profile'),
    path('updateprofile/', views.update_profile, name='update_profile'),
    path('passwordchange/', views.password_change, name='password_change'),
    path('check-unique/', views.check_unique, name='check_unique'),
]

evocom/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django.utils.crypto import get_random_string


class User(AbstractUser):
    pass

class UserDetails(models.Model):
    ROLE_CHOICES = [
        ('member', 'Member'),
        ('organizer', 'Event Organizer'),
        ('community_admin', 'Community Admin'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='details')
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    gender = models.CharField(max_length=10, blank=True, null=True)
    place = models.CharField(max_length=255, blank=True, null=True)
    address = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.username

class PasswordResetToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='password_reset_tokens')
    token = models.CharField(max_length=100, unique=True)
    expiry = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = get_random_string(length=32)
        if not self.expiry:
            self.expiry = timezone.now() + timedelta(minutes=15)
        super().save(*args, **kwargs)

    def is_valid(self):
        return self.expiry > timezone.now()

    def __str__(self):
        return f"Token for {self.user.username} expires at {self.expiry}"

evocom/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.models import User

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

evocom/users/views.py
from django.contrib.auth import authenticate, login, logout,update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.utils.crypto import get_random_string
from evocom import settings
from .models import PasswordResetToken, User, UserDetails
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from .decorators import nocache
from communities.models import Community



def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about-us.html')

def contacts(request):
    return render(request, 'contact.html')

@login_required
@nocache
def admin_index(request):
    return render(request, 'user/admin_index.html')
@login_required
@nocache
def community_admin_index(request):
    return render(request, 'user/community_admin_index.html')
@login_required
@nocache
def member_index(request):
    return render(request, 'user/member_index.html')

@login_required
@nocache
def user_profile(request):
    user = request.user
    user_details = user.details
    if request.method == 'POST':
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user_details.phone_number = request.POST.get('phone_number')
        user_details.gender = request.POST.get('gender')
        user_details.place = request.POST.get('place')
        user_details.address = request.POST.get('address')
        user.save()
        user_details.save()
        messages.success(request, 'Profile updated successfully!')
        return redirect('users:user_profile')

    return render(request, 'user/profile.html', {'user': user, 'user_details': user_details})

def login_page(request):
    if request.user.is_authenticated:
        return redirect('users:member_index')
    return render(request, 'user/login.html')

def send_welcome_email(user):
    subject = 'Welcome to EvoCom'
    context = {'user': user}
    html_content = render_to_string('user/welcome_mail.html', context)
    text_content = strip_tags(html_content)
    email = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [user.email])
    email.attach_alternative(html_content, 'text/html')
    email.send()

def send_password_reset_email(user, token):
    reset_url = f'{settings.SITE_URL}/reset_password/{token}/'
    subject = 'Password Reset Request'
    context = {
        'user': user,
        'reset_url': reset_url,
    }
    html_content = render_to_string('user/password_reset_email.html', context)
    text_content = strip_tags(html_content)
    email = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [user.email])
    email.attach_alternative(html_content, 'text/html')
    email.send()

@require_POST
def register_view(request):
    username = request.POST.get('username')
    email = request.POST.get('email')
    password1 = request.POST.get('password1')
    password2 = request.POST.get('password2')

    if password1 != password2:
        return render(request, 'user/register.html', {'error': 'Passwords do not match'})

    try:
        user = User.objects.create_user(username=username, email=email, password=password1)
        UserDetails.objects.create(user=user)
        send_welcome_email(user)
        return redirect('users:login')

    except Exception as e:
        return render(request, 'user/register.html', {'error': str(e)})

def login_view(request):
    if request.user.is_authenticated:
        user_details, created = UserDetails.objects.get_or_create(user=request.user)
        if user_details.role == "admin":
            return redirect('users:admin_index')
        profile_complete = user_details.role and user_details.phone_number and user_details.place
        if profile_complete:
            if user_details.role == "member":
                return redirect('users:member_index')
            if user_details.role == "community_admin":
                try:
                    community = Community.objects.get(admin=request.user)
                    has_community = community.name and community.description
                    if has_community:
                        return redirect('users:community_admin_index')
                    else:
                        return redirect('communities:create_community')
                except Community.DoesNotExist:
                    return redirect('communities:create_community')
        else:
            return redirect('users:select_user_type')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            user_details, created = UserDetails.objects.get_or_create(user=user)
            if user_details.role == "admin":
                return redirect('users:admin_index')
            profile_complete = user_details.role and user_details.phone_number and user_details.place
            if profile_complete:
                if user_details.role == "member":
                    return redirect('users:member_index')
                if user_details.role == "community_admin":
                    try:
                        community = Community.objects.get(admin=user)
                        has_community = community.name and community.description
                        if has_community:
                            return redirect('users:community_admin_index')
                        else:
                            return redirect('communities:create_community')
                    except Community.DoesNotExist:
                        return redirect('communities:create_community')
            else:
                return redirect('users:select_user_type')
        else:
            return render(request, 'user/login.html', {'error': 'Invalid username or password.'})

    return render(request, 'user/login.html')

def user_logout(request):
    logout(request)
    return redirect('users:index')

@login_required
def select_user_type(request):
    if request.method == 'POST':
        user_details = request.user.details
        role = request.POST.get('role')
        user_details.role = role
        user_details.save()
        return redirect('users:complete_profile')

    roles = UserDetails.ROLE_CHOICES
    context = {
        'roles': roles
    }
    return render(request, 'user/select_user_type.html', context)

@login_required
def complete_profile(request):
    user = request.user
    user_details = user.details
    if request.method == 'POST':
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user_details.phone_number = request.POST.get('phone_number')
        user_details.gender = request.POST.get('gender')
        user_details.place = request.POST.get('place')
        user_details.address = request.POST.get('address')
        user.save()
        user_details.save()
        messages.success(request, 'Profile updated successfully!')
        if user_details.role == "member":
            return redirect('users:member_index')
        if user_details.role == "community_admin":
            return redirect('communities:create_community')
        if user_details.role == "admin":
            return redirect('users:admin_index')

    return render(request, 'user/profile_completion.html')

def password_reset_request(request):
    if request.method == "POST":
        email = request.POST.get('email')
        associated_users = User.objects.filter(email=email)
        if associated_users.exists():
            for user in associated_users:
                token = PasswordResetToken.objects.create(user=user)
                send_password_reset_email(user, token.token)
            return HttpResponse('A password reset link has been sent to your email.')
        else:
            return HttpResponse('No user is associated with this email address.')
    return render(request, 'user/forgot_password.html')

def reset_password(request, token):
    reset_token = PasswordResetToken.objects.filter(token=token, expiry__gt=timezone.now()).first()
    if not reset_token:
        return HttpResponse("Invalid or expired token.")
    
    if request.method == "POST":
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 == password2:
            reset_token.user.set_password(password1)
            reset_token.user.save()
            reset_token.delete()
            return HttpResponse("Your password has been reset successfully.")
        else:
            return HttpResponse("Passwords do not match.")
    
    return render(request, 'user/reset_password.html', {'token': token})

@login_required
def update_profile(request):
    user = request.user
    user_details = user.details
    if request.method == 'POST':
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user_details.phone_number = request.POST.get('phone_number')
        user_details.place = request.POST.get('place')
        user_details.address = request.POST.get('address')
        user.save()
        user_details.save()
        messages.success(request, 'Profile updated successfully!')
        return redirect('users:user_profile')
    return render(request, 'user/profile.html', {'user': user, 'user_details': user_details})
@login_required
def password_change(request):
    if request.method == 'POST':
        user = request.user

evocom/templates/user/forgot_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <title>Forgot Password</title>
</head>
<body>
    <div class="container">
        <form method="post" action="{% url 'users:password_reset_request' %}">
            {% csrf_token %}
            <h1>Forgot Password</h1>
            <input type="email" name="email" placeholder="Enter your email" required />
            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

evocom/templates/user/member_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EvoCom</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo">
                <a href="{% url 'users:member_index' %}">
                    <img src="{% static 'img/logo-black.png' %}" height="100px" alt="logo">
                </a>
            </div>
            <div class="nav-menu">
                <nav class="mainmenu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'users:member_index' %}">Home</a></li>
                        <li><a href="{% url 'communities:show_communities' %}">Explore</a></li>
                        <li><a href="{% url 'communities:joined_communities' %}">My Communities</a></li>
                        <li><a href="{% url 'users:user_profile' %}">Hi, {{ user.username }}</a></li>
                    </ul>
                </nav>
                <a href="{% url 'users:logout' %}" class="primary-btn top-btn">logout</a>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Hero Section Begin -->
    <section class="hero-section set-bg" data-setbg="{% static 'img/hero.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <div class="hero-text">
                        <span>Connect, Create, Celebrate</span>
                        <h2>Your Community Events Made Simple</h2>
                        <a href="#" class="primary-btn">Join Us</a>
                    </div>
                </div>
                <div class="col-lg-5">
                    <img src="{% static 'img/hero-right.png' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Counter Section Begin -->
    <section class="counter-section bg-gradient">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="counter-text">
                        <span>Why worry now when you can</span>
                        <h3>Count Every Second <br />Until the Event</h3>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="cd-timer" id="countdown">
                        <div class="cd-item">
                            <span>40</span>
                            <p>Days</p>
                        </div>
                        <div class="cd-item">
                            <span>18</span>
                            <p>Hours</p>
                        </div>
                        <div class="cd-item">
                            <span>46</span>
                            <p>Minutes</p>
                        </div>
                        <div class="cd-item">
                            <span>32</span>
                            <p>Seconds</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Counter Section End -->

    <!-- Home About Section Begin -->
    <section class="home-about-section spad" id="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="ha-pic">
                        <img src="{% static 'img/h-about.jpg' %}" alt="About EvoCom">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="ha-text">
                        <h2>About EvoCom</h2>
                        <p>EvoCom is your ultimate community event management platform, designed to simplify the way you
                            plan, organize, and manage events. Whether you're hosting a local gathering, a
                            community-wide celebration, or a public event, EvoCom provides the tools you need to ensure
                            success.</p>
                        <ul>
                            <li><span class="icon_check"></span> Seamless Event Creation and Management</li>
                            <li><span class="icon_check"></span> Secure Online Registration and Payment Processing</li>
                            <li><span class="icon_check"></span> Real-Time Notifications and Event Updates</li>
                            <li><span class="icon_check"></span> Comprehensive Analytics and Reporting</li>
                            <li><span class="icon_check"></span> Volunteer Coordination and Task Assignment</li>
                        </ul>
                        <a href="#" class="ha-btn">Discover Now</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Home About Section End -->
    <!-- Features Section Begin -->
    <section class="pricing-section set-bg spad" data-setbg="{% static 'img/pricing-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>User Features</h2>
                        <p>Explore the features tailored for different users</p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-8">
                    <div class="price-item">
                        <h4>Community Members</h4>
                        <ul>
                            <li>Profile Management</li>
                            <li>Event Discovery</li>
                            <li>Event Registration</li>
                            <li>Fee Management</li>
                            <li>Notification Centre</li>
                            <li>Event Reminders</li>
                        </ul>
                        <a href="#" class="price-btn">Join Now <span class="arrow_right"></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="price-item top-rated">
                        <h4>Event Organizers</h4>
                        <ul>
                            <li>Event Creation</li>
                            <li>Attendee Management</li>
                            <li>Fee Collection</li>
                            <li>Volunteer Management</li>
                            <li>Analytics Dashboard</li>
                            <li>Customizable Email Templates</li>
                        </ul>
                        <a href="#" class="price-btn">Get Started <span class="arrow_right"></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="price-item">
                        <h4>Community Admins</h4>
                        <ul>
                            <li>Community Creation</li>
                            <li>Community Event Management</li>
                            <li>Member Management</li>
                            <li>Fee Management</li>
                            <li>Notification Centre</li>
                            <li>Analytics Dashboard</li>
                        </ul>
                        <a href="#" class="price-btn">Manage Now <span class="arrow_right"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Features Section End -->
    <!-- Newslatter Section Begin -->
    <section class="newslatter-section">

    </section>
    <section class="counter-section bg-gradient">
        <div class="container">
            <div class="newslatter-inner">
                <div class="ni-text">
                    <h3>Subscribe to Our Newsletter</h3>
                    <p>Stay updated with our latest news and events</p>
                </div>
                <form action="#" class="ni-form">
                    <input type="email" placeholder="Your email" required>
                    <button type="submit">Subscribe</button>
                </form>
            </div>
        </div>
    </section>
    <!-- Newsletter Section End -->

    <!-- Contact Section Begin -->
    <section class="contact-section spad" id="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="section-title">
                        <h2>Contact Us</h2>
                        <p>Get in touch with us for any inquiries</p>
                    </div>
                    <div class="cs-text">
                        <div class="ct-address">
                            <span>Address:</span>
                            <p>EvoCom Solutions, Kottayam, Kerala , India, 686572</p>
                        </div>
                        <ul>
                            <li>
                                <span>Phone:</span>
                                (+91)-8547861240
                            </li>
                            <li>
                                <span>Email:</span>
                                <a style="color:black;" href="mailto:evocomindia@gmail.com?subject=Inquiry&body=Add what you want to inquire about" target="_blank">evocomindia@gmail.com</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="cs-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3932.8586947398217!2d76.6010530745053!3d9.693099378241412!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b07d30000daf98d%3A0x300798406b0bbbc4!2sAiswarya%20House!5e0!3m2!1sen!2sin!4v1721726944410!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->


    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-text">
                        <div class="ft-logo">
                            <a href="#" class="footer-logo"><img src="{% static 'img/footer-logo.png' %}" height="100"
                                    alt="EvoCom Logo"></a>
                        </div>
                        <div class="copyright-text">
                            <p>
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved |
                                <a href="#" target="_blank">EvoCom</a>
                            </p>
                        </div>
                        <div class="ft-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->


    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <!--<script src="{% static 'js/jquery.countdown.min.js' %}"></script>-->
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

evocom/templates/user/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset Request</title>
</head>
<body>
    <p>Hi {{ user.username }},</p>
    <p>You requested a password reset for your account. Please click the link below to reset your password:</p>
    <p><a href="{{ reset_url }}">Reset Password</a></p>
    <p>This link will expire in 15 minutes</p>
    <p>If you did not request a password reset, please ignore this email.</p>
    <p>Thank you,</p>
    <p>The EvoCom Team</p>
</body>
</html>

evocom/templates/user/reset_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <title>Reset Password</title>
</head>
<body>
    <div class="container">
        <form method="post" action="{% url 'users:reset_password' token %}">
            {% csrf_token %}
            <h1>Reset Password</h1>
            <input type="password" name="password1" placeholder="New Password" required />
            <input type="password" name="password2" placeholder="Confirm New Password" required />
            <button type="submit">Reset Password</button>
        </form>
    </div>
</body>
</html>