evocom/evocom/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from evocom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('users/', include('users.urls')),
    path('communities/', include('communities.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

evocom/users/urls.py
from django.urls import path
from . import views

app_name = 'users' 
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contacts', views.contacts, name='contacts'),
    path('profile/', views.user_profile, name='user_profile'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_page, name='login'),
    path('loginfn/', views.login_view, name='loginfn'),
    path('logout/', views.user_logout, name='logout'),
    path('complete-profile/', views.complete_profile, name='complete_profile'),
    path('admin_index/', views.admin_index, name='admin_index'),
    path('member_index/', views.member_index, name='member_index'),
    path('community_admin_index/', views.community_admin_index, name='community_admin_index'),
    path('forgot_password/', views.password_reset_request, name='password_reset_request'),
    path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
    path('select_user_type/', views.select_user_type, name='select_user_type'),
    path('complete_profile/', views.complete_profile, name='complete_profile'),
    path('updateprofile/', views.update_profile, name='update_profile'),
    path('passwordchange/', views.password_change, name='password_change'),
    path('check-unique/', views.check_unique, name='check_unique'),
]

evocom/templates/blog.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Manup Template">
    <meta name="keywords" content="Manup, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Manup | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="css/style.css" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section header-normal">
        <div class="container">
            <div class="logo">
                <a href="./index.html">
                    <img src="img/logo.png" alt="">
                </a>
            </div>
            <div class="nav-menu">
                <nav class="mainmenu mobile-menu">
                    <ul>
                        <li><a href="./index.html">Home</a></li>
                        <li><a href="./about-us.html">About</a></li>
                        <li><a href="./speaker.html">Speakers</a>
                            <ul class="dropdown">
                                <li><a href="#">Jayden</a></li>
                                <li><a href="#">Sara</a></li>
                                <li><a href="#">Emma</a></li>
                                <li><a href="#">Harriet</a></li>
                            </ul>
                        </li>
                        <li><a href="./schedule.html">Schedule</a></li>
                        <li class="active"><a href="./blog.html">Blog</a></li>
                        <li><a href="./contact.html">Contacts</a></li>
                    </ul>
                </nav>
                <a href="#" class="primary-btn top-btn"><i class="fa fa-ticket"></i> Ticket</a>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>News Latest</h2>
                        <div class="bt-option">
                            <a href="#">Home</a>
                            <span>Our Blogs</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="blog-item set-bg" data-setbg="img/blog/blog-1.jpg">
                                <div class="bi-tag bg-gradient">Foody</div>
                                <div class="bi-text">
                                    <h5><a href="./blog-details.html">Google's AI Assistant Aims to Transcend the Smart Speaker</a></h5>
                                    <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="blog-item set-bg" data-setbg="img/blog/blog-2.jpg">
                                <div class="bi-tag bg-gradient">Foody</div>
                                <div class="bi-text">
                                    <h5><a href="./blog-details.html">Free Classifiends Using Them To Promote</a></h5>
                                    <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="blog-item set-bg large-item" data-setbg="img/blog/blog-4.jpg">
                        <div class="bi-tag bg-gradient">Business</div>
                        <div class="bi-text">
                            <h3><a href="./blog-details.html">"Inspired By Modiji, Will Make Biopic": BJP's Ravi Kishan</a></h3>
                            <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="blog-item set-bg" data-setbg="img/blog/blog-7.jpg">
                                <div class="bi-tag bg-gradient">Foody</div>
                                <div class="bi-text">
                                    <h5><a href="./blog-details.html">The ZenBook With a Touchpad That Lights Up</a></h5>
                                    <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="blog-item set-bg" data-setbg="img/blog/blog-8.jpg">
                                <div class="bi-tag bg-gradient">Foody</div>
                                <div class="bi-text">
                                    <h5><a href="./blog-details.html">Is the Detel Posh a Posh Speaker?</a></h5>
                                    <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="blog-item set-bg large-item" data-setbg="img/blog/blog-3.jpg">
                        <div class="bi-tag bg-gradient">Marketing</div>
                        <div class="bi-text">
                            <h3><a href="./blog-details.html">Lok Sabha Elections 2019 - In BJP, Only ''Tai'' Can Admonish Me: PM Modi On Sumitra
                                Mahajan</a></h3>
                            <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="blog-item set-bg" data-setbg="img/blog/blog-5.jpg">
                                <div class="bi-tag bg-gradient">Design</div>
                                <div class="bi-text">
                                    <h5><a href="./blog-details.html">The Biggest Stories Of January 06, 2019</a></h5>
                                    <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="blog-item set-bg" data-setbg="img/blog/blog-6.jpg">
                                <div class="bi-tag bg-gradient">UX/UI</div>
                                <div class="bi-text">
                                    <h5><a href="./blog-details.html">Alexa Can Now Show You Things!</a></h5>
                                    <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="blog-item set-bg" data-setbg="img/blog/blog-9.jpg">
                        <div class="bi-tag bg-gradient">Marketing</div>
                        <div class="bi-text">
                            <h3><a href="./blog-details.html">"Still Waiting For BJP To Make Me Chief Minister": Goa Assembly Speaker</a></h3>
                            <span><i class="fa fa-clock-o"></i> 19th May, 2019</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="load-more blog-more">
                <a href="#" class="primary-btn">Load More</a>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="partner-logo owl-carousel">
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="img/partner-logo/logo-1.png" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="img/partner-logo/logo-2.png" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="img/partner-logo/logo-3.png" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="img/partner-logo/logo-4.png" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="img/partner-logo/logo-5.png" alt="">
                    </div>
                </a>
                <a href="#" class="pl-table">
                    <div class="pl-tablecell">
                        <img src="img/partner-logo/logo-6.png" alt="">
                    </div>
                </a>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-text">
                        <div class="ft-logo">
                            <a href="#" class="footer-logo"><img src="img/footer-logo.png" alt=""></a>
                        </div>
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Speakers</a></li>
                            <li><a href="#">Schedule</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                        <div class="copyright-text"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></div>
                        <div class="ft-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery.countdown.min.js"></script>
    <script src="js/jquery.slicknav.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/main.js"></script>
</body>

</html>

evocom/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Manup Template">
    <meta name="keywords" content="Manup, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EvoCom</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo">
                <a href="{% url 'users:index' %}">
                    <img src="{% static 'img/logo-black.png' %}" height="100px" alt="logo">
                </a>
            </div>
            <div class="nav-menu">
                <nav class="mainmenu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'users:index' %}">Home</a></li>
                        <li><a href="#about-section">About</a></li>
                        <li><a href="#contact-section">Contacts</a></li>
                    </ul>
                </nav>
                <a href="{% url 'users:login' %}" class="primary-btn top-btn">Signup Now</a>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Hero Section Begin -->
    <section class="hero-section set-bg" data-setbg="{% static 'img/hero.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <div class="hero-text">
                        <span>Connect, Create, Celebrate</span>
                        <h2>Your Community Events Made Simple</h2>
                        <a href="{% url 'users:login' %}" class="primary-btn">Join Us</a>
                    </div>
                </div>
                <div class="col-lg-5">
                    <img src="{% static 'img/hero-right.png' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Counter Section Begin -->
    <section class="counter-section bg-gradient">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="counter-text">
                        <span>Why worry now when you can</span>
                        <h3>Count Every Second <br />Until the Event</h3>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="cd-timer" id="countdown">
                        <div class="cd-item">
                            <span>40</span>
                            <p>Days</p>
                        </div>
                        <div class="cd-item">
                            <span>18</span>
                            <p>Hours</p>
                        </div>
                        <div class="cd-item">
                            <span>46</span>
                            <p>Minutes</p>
                        </div>
                        <div class="cd-item">
                            <span>32</span>
                            <p>Seconds</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Counter Section End -->

    <!-- Home About Section Begin -->
    <section class="home-about-section spad" id="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="ha-pic">
                        <img src="{% static 'img/h-about.jpg' %}" alt="About EvoCom">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="ha-text">
                        <h2>About EvoCom</h2>
                        <p>EvoCom is your ultimate community event management platform, designed to simplify the way you
                            plan, organize, and manage events. Whether you're hosting a local gathering, a
                            community-wide celebration, or a public event, EvoCom provides the tools you need to ensure
                            success.</p>
                        <ul>
                            <li><span class="icon_check"></span> Seamless Event Creation and Management</li>
                            <li><span class="icon_check"></span> Secure Online Registration and Payment Processing</li>
                            <li><span class="icon_check"></span> Real-Time Notifications and Event Updates</li>
                            <li><span class="icon_check"></span> Comprehensive Analytics and Reporting</li>
                            <li><span class="icon_check"></span> Volunteer Coordination and Task Assignment</li>
                        </ul>
                        <a href="{% url 'users:login' %}" class="ha-btn">Discover Now</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Home About Section End -->
    <!-- Features Section Begin -->
    <section class="pricing-section set-bg spad" data-setbg="{% static 'img/pricing-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>User Features</h2>
                        <p>Explore the features tailored for different users</p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-8">
                    <div class="price-item">
                        <h4>Community Members</h4>
                        <ul>
                            <li>Profile Management</li>
                            <li>Event Discovery</li>
                            <li>Event Registration</li>
                            <li>Fee Management</li>
                            <li>Notification Centre</li>
                            <li>Event Reminders</li>
                        </ul>
                        <a href="{% url 'users:login' %}" class="price-btn">Join Now <span class="arrow_right"></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="price-item top-rated">
                        <h4>Event Organizers</h4>
                        <ul>
                            <li>Event Creation</li>
                            <li>Attendee Management</li>
                            <li>Fee Collection</li>
                            <li>Volunteer Management</li>
                            <li>Analytics Dashboard</li>
                            <li>Customizable Email Templates</li>
                        </ul>
                        <a href="{% url 'users:login' %}" class="price-btn">Get Started <span class="arrow_right"></span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="price-item">
                        <h4>Community Admins</h4>
                        <ul>
                            <li>Community Creation</li>
                            <li>Community Event Management</li>
                            <li>Member Management</li>
                            <li>Fee Management</li>
                            <li>Notification Centre</li>
                            <li>Analytics Dashboard</li>
                        </ul>
                        <a href="{% url 'users:login' %}" class="price-btn">Manage Now <span class="arrow_right"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Features Section End -->
    <!-- Newslatter Section Begin -->
    <section class="counter-section bg-gradient">
        <div class="container">
            <div class="newslatter-inner">
                <div class="ni-text">
                    <h3>Subscribe to Our Newsletter</h3>
                    <p>Stay updated with our latest news and events</p>
                </div>
                <form action="#" class="ni-form">
                    <input type="email" placeholder="Your email" required>
                    <button type="submit">Subscribe</button>
                </form>
            </div>
        </div>
    </section>
    <!-- Newsletter Section End -->

    <!-- Contact Section Begin -->
    <section class="contact-section spad" id="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="section-title">
                        <h2>Contact Us</h2>
                        <p>Get in touch with us for any inquiries</p>
                    </div>
                    <div class="cs-text">
                        <div class="ct-address">
                            <span>Address:</span>
                            <p>EvoCom Solutions, Kottayam, Kerala , India, 686572</p>
                        </div>
                        <ul>
                            <li>
                                <span>Phone:</span>
                                (+91)-8547861240
                            </li>
                            <li>
                                <span>Email:</span>
                                <a style="color:black;" href="mailto:evocomindia@gmail.com?subject=Inquiry&body=Add what you want to inquire about" target="_blank">evocomindia@gmail.com</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="cs-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3932.8586947398217!2d76.6010530745053!3d9.693099378241412!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b07d30000daf98d%3A0x300798406b0bbbc4!2sAiswarya%20House!5e0!3m2!1sen!2sin!4v1721726944410!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->


    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-text">
                        <div class="ft-logo">
                            <a href="#" class="footer-logo"><img src="{% static 'img/footer-logo.png' %}" height="100"
                                    alt="EvoCom Logo"></a>
                        </div>
                        <div class="copyright-text">
                            <p>
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved |
                                <a href="#" target="_blank">EvoCom</a>
                            </p>
                        </div>
                        <div class="ft-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->


    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <!--<script src="{% static 'js/jquery.countdown.min.js' %}"></script>-->
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

evocom/templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>